import type { AbstractProposition } from "../../src/domain/proposition";
import type { AbstractSyllogism } from "../../src/domain/syllogism";
import type { CarrollTriliteralDiagram } from "../helpers/carrollBookVIII";
import {
  carrollProposition,
  carrollSource,
  carrollSyllogism,
  type CarrollSourceMetadata,
} from "../helpers/carrollBookVIII";

export interface CarrollBookVIIISection2Case {
  readonly section: 2;
  readonly number: number;
  readonly source: CarrollSourceMetadata;
  readonly sourceText: readonly [string, string];
  readonly premises: AbstractSyllogism;
  readonly expected: CarrollTriliteralDiagram;
}

const A = (subject: Parameters<typeof carrollProposition>[1], predicate: Parameters<typeof carrollProposition>[2]): AbstractProposition =>
  carrollProposition("A", subject, predicate);
const E = (subject: Parameters<typeof carrollProposition>[1], predicate: Parameters<typeof carrollProposition>[2]): AbstractProposition =>
  carrollProposition("E", subject, predicate);
const I = (subject: Parameters<typeof carrollProposition>[1], predicate: Parameters<typeof carrollProposition>[2]): AbstractProposition =>
  carrollProposition("I", subject, predicate);

function diagram(
  emptyCells: CarrollTriliteralDiagram["emptyCells"],
  existence: CarrollTriliteralDiagram["existence"] = [],
): CarrollTriliteralDiagram {
  return { emptyCells, existence };
}

function section2Case(
  number: number,
  sourceText: readonly [string, string],
  firstPremise: AbstractProposition,
  secondPremise: AbstractProposition,
  expected: CarrollTriliteralDiagram,
): CarrollBookVIIISection2Case {
  return {
    section: 2,
    number,
    source: carrollSource(2, number),
    sourceText,
    premises: carrollSyllogism(firstPremise, secondPremise),
    expected,
  };
}

// The expected O/I anchors below were transcribed from the redrawn diagrams in
// Book VIII, Chapter II, “Answers to § 2” (printed pages 126–127). They are
// intentionally fixed data and are not generated by the production rules.
export const CARROLL_BOOK_VIII_SECTION_2 = [
  section2Case(1, ["No x are m", "No m′ are y"], E("x", "m"), E("m′", "y"),
    diagram(["SMP", "SMp", "SmP", "smP"])),
  section2Case(2, ["No x′ are m′", "All m′ are y"], E("x′", "m′"), A("m′", "y"),
    diagram(["Smp", "smP", "smp"], [{ type: "cell", cell: "SmP" }])),
  section2Case(3, ["Some x′ are m", "No m are y"], I("x′", "m"), E("m", "y"),
    diagram(["SMP", "sMP"], [{ type: "cell", cell: "sMp" }])),
  section2Case(4, ["All m are x", "All m′ are y′"], A("m", "x"), A("m′", "y′"),
    diagram(["SmP", "sMP", "sMp", "smP"], [
      { type: "boundary", cells: ["SMP", "SMp"] },
      { type: "boundary", cells: ["Smp", "smp"] },
    ])),
  section2Case(5, ["All m′ are x", "All m′ are y′"], A("m′", "x"), A("m′", "y′"),
    diagram(["SmP", "smP", "smp"], [{ type: "cell", cell: "Smp" }])),
  section2Case(6, ["All x′ are m′", "No y′ are m"], A("x′", "m′"), E("y′", "m"),
    diagram(["SMp", "sMP", "sMp"], [
      { type: "boundary", cells: ["smP", "smp"] },
    ])),
  section2Case(7, ["All x are m", "All y′ are m′"], A("x", "m"), A("y′", "m′"),
    diagram(["SMp", "SmP", "Smp", "sMp"], [
      { type: "cell", cell: "SMP" },
      { type: "cell", cell: "smp" },
    ])),
  section2Case(8, ["Some m′ are x′", "No m are y"], I("m′", "x′"), E("m", "y"),
    diagram(["SMP", "sMP"], [
      { type: "boundary", cells: ["smP", "smp"] },
    ])),
  section2Case(9, ["All m are x′", "No m are y"], A("m", "x′"), E("m", "y"),
    diagram(["SMP", "SMp", "sMP"], [{ type: "cell", cell: "sMp" }])),
  section2Case(10, ["No m are x′", "No y are m′"], E("m", "x′"), E("y", "m′"),
    diagram(["SmP", "sMP", "sMp", "smP"])),
  section2Case(11, ["No x′ are m′", "No m are y"], E("x′", "m′"), E("m", "y"),
    diagram(["SMP", "sMP", "smP", "smp"])),
  section2Case(12, ["Some x are m", "All y′ are m"], I("x", "m"), A("y′", "m"),
    diagram(["Smp", "smp"], [
      { type: "boundary", cells: ["SMP", "SMp"] },
      { type: "boundary", cells: ["SMp", "sMp"] },
    ])),
  section2Case(13, ["All x′ are m", "No m are y"], A("x′", "m"), E("m", "y"),
    diagram(["SMP", "sMP", "smP", "smp"], [{ type: "cell", cell: "sMp" }])),
  section2Case(14, ["Some x are m′", "All m are y"], I("x", "m′"), A("m", "y"),
    diagram(["SMp", "sMp"], [
      { type: "boundary", cells: ["SMP", "sMP"] },
      { type: "boundary", cells: ["SmP", "Smp"] },
    ])),
  section2Case(15, ["No m′ are x′", "All y are m"], E("m′", "x′"), A("y", "m"),
    diagram(["SmP", "smP", "smp"], [
      { type: "boundary", cells: ["SMP", "sMP"] },
    ])),
  section2Case(16, ["All x are m′", "No y are m"], A("x", "m′"), E("y", "m"),
    diagram(["SMP", "SMp", "sMP"], [
      { type: "boundary", cells: ["SmP", "Smp"] },
    ])),
  section2Case(17, ["Some m′ are x", "No m′ are y′"], I("m′", "x"), E("m′", "y′"),
    diagram(["Smp", "smp"], [{ type: "cell", cell: "SmP" }])),
  section2Case(18, ["All x are m′", "Some m′ are y′"], A("x", "m′"), I("m′", "y′"),
    diagram(["SMP", "SMp"], [
      { type: "boundary", cells: ["SmP", "Smp"] },
      { type: "boundary", cells: ["Smp", "smp"] },
    ])),
  section2Case(19, ["All m are x", "Some m are y′"], A("m", "x"), I("m", "y′"),
    diagram(["sMP", "sMp"], [
      { type: "boundary", cells: ["SMP", "SMp"] },
      { type: "cell", cell: "SMp" },
    ])),
  section2Case(20, ["No x′ are m", "Some y are m"], E("x′", "m"), I("y", "m"),
    diagram(["sMP", "sMp"], [{ type: "cell", cell: "SMP" }])),
  section2Case(21, ["Some x′ are m′", "All y′ are m"], I("x′", "m′"), A("y′", "m"),
    diagram(["Smp", "smp"], [
      { type: "cell", cell: "smP" },
      { type: "boundary", cells: ["SMp", "sMp"] },
    ])),
  section2Case(22, ["No m are x", "Some m are y"], E("m", "x"), I("m", "y"),
    diagram(["SMP", "SMp"], [{ type: "cell", cell: "sMP" }])),
  section2Case(23, ["No m′ are x", "All y are m′"], E("m′", "x"), A("y", "m′"),
    diagram(["SMP", "SmP", "Smp", "sMP"], [{ type: "cell", cell: "smP" }])),
  section2Case(24, ["All m are x", "No y′ are m′"], A("m", "x"), E("y′", "m′"),
    diagram(["Smp", "sMP", "sMp", "smp"], [
      { type: "boundary", cells: ["SMP", "SMp"] },
    ])),
  section2Case(25, ["Some m are x", "No y′ are m"], I("m", "x"), E("y′", "m"),
    diagram(["SMp", "sMp"], [{ type: "cell", cell: "SMP" }])),
  section2Case(26, ["All m′ are x′", "Some y are m′"], A("m′", "x′"), I("y", "m′"),
    diagram(["SmP", "Smp"], [
      { type: "cell", cell: "smP" },
      { type: "boundary", cells: ["smP", "smp"] },
    ])),
  section2Case(27, ["Some m are x′", "No y′ are m′"], I("m", "x′"), E("y′", "m′"),
    diagram(["Smp", "smp"], [
      { type: "boundary", cells: ["sMP", "sMp"] },
    ])),
  section2Case(28, ["No x are m′", "All m are y′"], E("x", "m′"), A("m", "y′"),
    diagram(["SMP", "SmP", "Smp", "sMP"], [
      { type: "boundary", cells: ["SMp", "sMp"] },
    ])),
  section2Case(29, ["No x′ are m", "No m are y′"], E("x′", "m"), E("m", "y′"),
    diagram(["SMp", "sMP", "sMp"])),
  section2Case(30, ["No x are m", "Some y′ are m′"], E("x", "m"), I("y′", "m′"),
    diagram(["SMP", "SMp"], [
      { type: "boundary", cells: ["Smp", "smp"] },
    ])),
  section2Case(31, ["Some m′ are x", "All y′ are m"], I("m′", "x"), A("y′", "m"),
    diagram(["Smp", "smp"], [
      { type: "cell", cell: "SmP" },
      { type: "boundary", cells: ["SMp", "sMp"] },
    ])),
  section2Case(32, ["All x are m′", "All y are m"], A("x", "m′"), A("y", "m"),
    diagram(["SMP", "SMp", "SmP", "smP"], [
      { type: "cell", cell: "Smp" },
      { type: "cell", cell: "sMP" },
    ])),
] as const satisfies readonly CarrollBookVIIISection2Case[];
